// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxXqkQXvd95SQ30VaEpsKvCVt9nXF7TM',
    appId: '1:64878894302:web:d2047997cc7bfd2740f64f',
    messagingSenderId: '64878894302',
    projectId: 'stock-count-app-c381c',
    authDomain: 'stock-count-app-c381c.firebaseapp.com',
    storageBucket: 'stock-count-app-c381c.firebasestorage.app',
    measurementId: 'G-WERMN3L2DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIcoe89FTV-oDcA4F9gOQbt06iesEm9co',
    appId: '1:64878894302:android:dc3b22642d092cc040f64f',
    messagingSenderId: '64878894302',
    projectId: 'stock-count-app-c381c',
    storageBucket: 'stock-count-app-c381c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlDBmX17CINbudn40E0SP4lHtZfsCpvw',
    appId: '1:64878894302:ios:0f0a58939821491940f64f',
    messagingSenderId: '64878894302',
    projectId: 'stock-count-app-c381c',
    storageBucket: 'stock-count-app-c381c.firebasestorage.app',
    iosBundleId: 'com.example.stockCountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlDBmX17CINbudn40E0SP4lHtZfsCpvw',
    appId: '1:64878894302:ios:0f0a58939821491940f64f',
    messagingSenderId: '64878894302',
    projectId: 'stock-count-app-c381c',
    storageBucket: 'stock-count-app-c381c.firebasestorage.app',
    iosBundleId: 'com.example.stockCountApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzxXqkQXvd95SQ30VaEpsKvCVt9nXF7TM',
    appId: '1:64878894302:web:b100a0d51ad8092f40f64f',
    messagingSenderId: '64878894302',
    projectId: 'stock-count-app-c381c',
    authDomain: 'stock-count-app-c381c.firebaseapp.com',
    storageBucket: 'stock-count-app-c381c.firebasestorage.app',
    measurementId: 'G-WTFV7T3XTS',
  );
}
